/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Omar
 */
public class frmConsultaPersona extends javax.swing.JFrame {

    /**
     * Creates new form frmConsultaPersona
     */
    public frmConsultaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grupoBusqueda = new javax.swing.ButtonGroup();
        jPanelBuscar = new javax.swing.JPanel();
        jRCedula = new javax.swing.JRadioButton();
        jRNombre = new javax.swing.JRadioButton();
        jRApellido = new javax.swing.JRadioButton();
        lbtFiltrar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jTabbedRegistro = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lbtTotal_Registro = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtPersonas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lbtCedula_persona = new javax.swing.JLabel();
        txtCedula_Persona = new javax.swing.JTextField();
        txtApellido_Persona = new javax.swing.JTextField();
        lbtApellido_Persona = new javax.swing.JLabel();
        txtNombre_Persona = new javax.swing.JTextField();
        lbtNombre_Persona = new javax.swing.JLabel();
        lbtFecha_Persona = new javax.swing.JLabel();
        txtDirHab_Persona = new javax.swing.JTextField();
        lbtDirHab_Persona = new javax.swing.JLabel();
        lbtTelfijo_Persona = new javax.swing.JLabel();
        txtTelFijo_Persona = new javax.swing.JTextField();
        txtTelcel_Persona = new javax.swing.JTextField();
        lbtTelcel_Persona = new javax.swing.JLabel();
        txtCorreo_Persona = new javax.swing.JTextField();
        lbtCorreo_Persona = new javax.swing.JLabel();
        lbtProfesion_Persona = new javax.swing.JLabel();
        txtIglesiaProv_Persona = new javax.swing.JTextField();
        lbtBautizado_Persona = new javax.swing.JLabel();
        txtOcupacion_Persona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaObservacion_Persona = new javax.swing.JTextArea();
        lbtObservacion_Persona = new javax.swing.JLabel();
        lbtOcupación_Persona = new javax.swing.JLabel();
        txtBautizado_Persona = new javax.swing.JTextField();
        txtProfesion_Persona = new javax.swing.JTextField();
        txtFechaNac_Persona = new javax.swing.JTextField();
        lbtIglesia_Persona = new javax.swing.JLabel();
        txtMinisterio_Persona = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBuscar.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtrar Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jRCedula.setText("Cédula");

        jRNombre.setText("Nombre");

        jRApellido.setText("Apellido");

        lbtFiltrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        lbtFiltrar.setText("Filtrar por:");

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lbtFiltrar)
                .addGap(46, 46, 46)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jRCedula)
                        .addGap(18, 18, 18)
                        .addComponent(jRNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jRApellido))
                    .addComponent(txtBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtFiltrar)
                    .addComponent(jRCedula)
                    .addComponent(jRNombre)
                    .addComponent(jRApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedRegistro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        lbtTotal_Registro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtTotal_Registro.setText("Total Registros:");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir.png"))); // NOI18N
        btnSalir.setText("Salir");

        jtPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Personas", "Cedula", "Nombre", "Apellido", "Fecha Nac", "Dirección", "Telefono", "Celular", "Profesión", "Ocupación", "Correo", "Bautizo", "Iglesia Prov", "Observación", "Ministerio"
            }
        ));
        jtPersonas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jtPersonas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbtTotal_Registro)
                .addGap(204, 204, 204)
                .addComponent(btnSalir)
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtTotal_Registro)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        jTabbedRegistro.addTab("Listado de Personas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        lbtCedula_persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtCedula_persona.setText("Cédula: ");

        txtCedula_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtApellido_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtApellido_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtApellido_Persona.setText("Apellidos:");

        txtNombre_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtNombre_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtNombre_Persona.setText("Nombres:");

        lbtFecha_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtFecha_Persona.setText("Fecha de Nac:");

        txtDirHab_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtDirHab_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtDirHab_Persona.setText("Dirección de Hab:");

        lbtTelfijo_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtTelfijo_Persona.setText("Telefono Fijo: ");

        txtTelFijo_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTelcel_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtTelcel_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtTelcel_Persona.setText("Telefono Celular:");

        txtCorreo_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtCorreo_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtCorreo_Persona.setText("Correo:");

        lbtProfesion_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtProfesion_Persona.setText("Profesion:");

        txtIglesiaProv_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtBautizado_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtBautizado_Persona.setText("Bautizado:");

        txtOcupacion_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ministerio:");

        tAreaObservacion_Persona.setColumns(20);
        tAreaObservacion_Persona.setRows(5);
        jScrollPane2.setViewportView(tAreaObservacion_Persona);

        lbtObservacion_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtObservacion_Persona.setText("Observación:");

        lbtOcupación_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtOcupación_Persona.setText("Ocupación:");

        txtBautizado_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtProfesion_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFechaNac_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtIglesia_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtIglesia_Persona.setText("Iglesia de Procedencia: ");

        txtMinisterio_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtOcupación_Persona)
                    .addComponent(lbtBautizado_Persona)
                    .addComponent(lbtProfesion_Persona)
                    .addComponent(lbtCedula_persona)
                    .addComponent(lbtNombre_Persona)
                    .addComponent(lbtApellido_Persona)
                    .addComponent(lbtObservacion_Persona)
                    .addComponent(lbtTelfijo_Persona)
                    .addComponent(lbtDirHab_Persona)
                    .addComponent(lbtFecha_Persona))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtProfesion_Persona, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelFijo_Persona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbtTelcel_Persona))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lbtCorreo_Persona)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo_Persona)
                            .addComponent(txtTelcel_Persona)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBautizado_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(lbtIglesia_Persona)
                        .addGap(18, 18, 18)
                        .addComponent(txtIglesiaProv_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNac_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirHab_Persona)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtOcupacion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMinisterio_Persona)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtCedula_persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtNombre_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtApellido_Persona)
                    .addComponent(txtApellido_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaNac_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtFecha_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirHab_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtDirHab_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelFijo_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtTelfijo_Persona)
                    .addComponent(lbtTelcel_Persona)
                    .addComponent(txtTelcel_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfesion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtProfesion_Persona)
                    .addComponent(lbtCorreo_Persona)
                    .addComponent(txtCorreo_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBautizado_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtIglesia_Persona)
                        .addComponent(txtIglesiaProv_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbtBautizado_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOcupacion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtOcupación_Persona))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMinisterio_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtObservacion_Persona)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedRegistro.addTab("Registro Individual", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedRegistro))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalir;
    public javax.swing.ButtonGroup grupoBusqueda;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanelBuscar;
    public javax.swing.JRadioButton jRApellido;
    public javax.swing.JRadioButton jRCedula;
    public javax.swing.JRadioButton jRNombre;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedRegistro;
    public javax.swing.JTable jtPersonas;
    public javax.swing.JLabel lbtApellido_Persona;
    public javax.swing.JLabel lbtBautizado_Persona;
    public javax.swing.JLabel lbtCedula_persona;
    public javax.swing.JLabel lbtCorreo_Persona;
    public javax.swing.JLabel lbtDirHab_Persona;
    public javax.swing.JLabel lbtFecha_Persona;
    private javax.swing.JLabel lbtFiltrar;
    public javax.swing.JLabel lbtIglesia_Persona;
    public javax.swing.JLabel lbtNombre_Persona;
    public javax.swing.JLabel lbtObservacion_Persona;
    private javax.swing.JLabel lbtOcupación_Persona;
    public javax.swing.JLabel lbtProfesion_Persona;
    public javax.swing.JLabel lbtTelcel_Persona;
    public javax.swing.JLabel lbtTelfijo_Persona;
    public javax.swing.JLabel lbtTotal_Registro;
    public javax.swing.JTextArea tAreaObservacion_Persona;
    public javax.swing.JTextField txtApellido_Persona;
    public javax.swing.JTextField txtBautizado_Persona;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCedula_Persona;
    public javax.swing.JTextField txtCorreo_Persona;
    public javax.swing.JTextField txtDirHab_Persona;
    public javax.swing.JTextField txtFechaNac_Persona;
    public javax.swing.JTextField txtIglesiaProv_Persona;
    public javax.swing.JTextField txtMinisterio_Persona;
    public javax.swing.JTextField txtNombre_Persona;
    public javax.swing.JTextField txtOcupacion_Persona;
    public javax.swing.JTextField txtProfesion_Persona;
    public javax.swing.JTextField txtTelFijo_Persona;
    public javax.swing.JTextField txtTelcel_Persona;
    // End of variables declaration//GEN-END:variables
}
