
package Vista;

/**
 *
 * @author usuario
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuPersonas = new javax.swing.JMenuItem();
        jMenuItemIglesias = new javax.swing.JMenuItem();
        jMenuMinisterio = new javax.swing.JMenuItem();
        jMenuProfesion = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsultaPersonas = new javax.swing.JMenuItem();
        jMenuItemConsultaIglesias = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBarPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Inicio.png"))); // NOI18N
        jMenuInicio.setText("Inicio");
        jMenuInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBarPrincipal.add(jMenuInicio);

        jMenuRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Archivo.png"))); // NOI18N
        jMenuRegistros.setText("Registros");
        jMenuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/persona.png"))); // NOI18N
        jMenuPersonas.setText("Personas");
        jMenuRegistros.add(jMenuPersonas);

        jMenuItemIglesias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemIglesias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Iglesia.png"))); // NOI18N
        jMenuItemIglesias.setText("Iglesias");
        jMenuRegistros.add(jMenuItemIglesias);

        jMenuMinisterio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuMinisterio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cruz.png"))); // NOI18N
        jMenuMinisterio.setText("Ministerio");
        jMenuRegistros.add(jMenuMinisterio);

        jMenuProfesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuProfesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/profesion.png"))); // NOI18N
        jMenuProfesion.setText("Profesión");
        jMenuProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfesionActionPerformed(evt);
            }
        });
        jMenuRegistros.add(jMenuProfesion);

        jMenuBarPrincipal.add(jMenuRegistros);

        jMenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Consultas.png"))); // NOI18N
        jMenuConsulta.setText("Consultas");
        jMenuConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemConsultaPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemConsultaPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clientes.png"))); // NOI18N
        jMenuItemConsultaPersonas.setText("Personas");
        jMenuItemConsultaPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaPersonasActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaPersonas);

        jMenuItemConsultaIglesias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemConsultaIglesias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Iglesia.png"))); // NOI18N
        jMenuItemConsultaIglesias.setText("Iglesias");
        jMenuConsulta.add(jMenuItemConsultaIglesias);

        jMenuBarPrincipal.add(jMenuConsulta);

        jMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Consultas.png"))); // NOI18N
        jMenuReportes.setText("Reportes");
        jMenuReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBarPrincipal.add(jMenuReportes);

        jMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Configuraciones.png"))); // NOI18N
        jMenuPrincipal.setText("Configuraciones");
        jMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/usuarios.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuarios");
        jMenuPrincipal.add(jMenuItemUsuario);

        jMenuBarPrincipal.add(jMenuPrincipal);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir1.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBarPrincipal.add(jMenuSalir);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuProfesionActionPerformed

    private void jMenuItemConsultaPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultaPersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBarPrincipal;
    public javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItemConsultaIglesias;
    public javax.swing.JMenuItem jMenuItemConsultaPersonas;
    public javax.swing.JMenuItem jMenuItemIglesias;
    public javax.swing.JMenuItem jMenuItemUsuario;
    public javax.swing.JMenuItem jMenuMinisterio;
    public javax.swing.JMenuItem jMenuPersonas;
    public javax.swing.JMenu jMenuPrincipal;
    public javax.swing.JMenuItem jMenuProfesion;
    public javax.swing.JMenu jMenuRegistros;
    private javax.swing.JMenu jMenuReportes;
    public javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
