/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author usuario
 */
public class frmPersona extends javax.swing.JFrame {

    /**
     * Creates new form frmPersona
     */
    public frmPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbtId_Persona = new javax.swing.JLabel();
        lbtCedula_persona = new javax.swing.JLabel();
        lbtNombre_Persona = new javax.swing.JLabel();
        lbtApellido_Persona = new javax.swing.JLabel();
        lbtFecha_Persona = new javax.swing.JLabel();
        lbtDirHab_Persona = new javax.swing.JLabel();
        lbtTelfijo_Persona = new javax.swing.JLabel();
        lbtTelcel_Persona = new javax.swing.JLabel();
        lbtProfesion_Persona = new javax.swing.JLabel();
        lbtCorreo_Persona = new javax.swing.JLabel();
        lbtBautizado_Persona = new javax.swing.JLabel();
        lbtIglesia_Persona = new javax.swing.JLabel();
        lbtObservacion_Persona = new javax.swing.JLabel();
        txtId_Persona = new javax.swing.JTextField();
        txtCedula_Persona = new javax.swing.JTextField();
        txtNombre_Persona = new javax.swing.JTextField();
        txtApellido_Persona = new javax.swing.JTextField();
        txtDirHab_Persona = new javax.swing.JTextField();
        txtTelFijo_Persona = new javax.swing.JTextField();
        txtTelcel_Persona = new javax.swing.JTextField();
        CboProfesion_Persona = new javax.swing.JComboBox();
        txtCorreo_Persona = new javax.swing.JTextField();
        CboBautizado_Persona = new javax.swing.JComboBox();
        txtIglesiaProv_Persona = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAreaObservacion_Persona = new javax.swing.JTextArea();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtOcupacion_Persona = new javax.swing.JTextField();
        lbtOcupación_Persona = new javax.swing.JLabel();
        CboMinisterio_Persona = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtFechaNac_Persona = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbtTotal_Registros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPersonas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        lbtFiltrar = new javax.swing.JLabel();
        jRCedula = new javax.swing.JRadioButton();
        jRNombre = new javax.swing.JRadioButton();
        jRApellido = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registro de Personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        lbtId_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtId_Persona.setText("ID Persona:");

        lbtCedula_persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtCedula_persona.setText("Cédula: ");

        lbtNombre_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtNombre_Persona.setText("Nombres:");

        lbtApellido_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtApellido_Persona.setText("Apellidos:");

        lbtFecha_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtFecha_Persona.setText("Fecha de Nac:");

        lbtDirHab_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtDirHab_Persona.setText("Dirección de Hab:");

        lbtTelfijo_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtTelfijo_Persona.setText("Telefono Fijo: ");

        lbtTelcel_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtTelcel_Persona.setText("Telefono Celular:");

        lbtProfesion_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtProfesion_Persona.setText("Profesion:");

        lbtCorreo_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtCorreo_Persona.setText("Correo:");

        lbtBautizado_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtBautizado_Persona.setText("Bautizado:");

        lbtIglesia_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtIglesia_Persona.setText("Iglesia de Procedencia: ");

        lbtObservacion_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtObservacion_Persona.setText("Observación:");

        txtId_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCedula_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNombre_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtApellido_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDirHab_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTelFijo_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTelcel_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CboProfesion_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCorreo_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CboBautizado_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CboBautizado_Persona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));

        txtIglesiaProv_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tAreaObservacion_Persona.setColumns(20);
        tAreaObservacion_Persona.setRows(5);
        jScrollPane1.setViewportView(tAreaObservacion_Persona);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");

        txtOcupacion_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtOcupación_Persona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtOcupación_Persona.setText("Ocupación:");

        CboMinisterio_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CboMinisterio_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboMinisterio_PersonaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ministerio:");

        txtFechaNac_Persona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtProfesion_Persona)
                            .addComponent(lbtTelfijo_Persona)
                            .addComponent(lbtDirHab_Persona)
                            .addComponent(lbtFecha_Persona)
                            .addComponent(lbtBautizado_Persona)
                            .addComponent(lbtOcupación_Persona)
                            .addComponent(lbtObservacion_Persona))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CboBautizado_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CboProfesion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(205, 205, 205)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelcel_Persona)
                                            .addComponent(txtCorreo_Persona)))
                                    .addComponent(txtDirHab_Persona, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtOcupacion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelFijo_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbtCorreo_Persona)
                                        .addComponent(lbtTelcel_Persona)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(lbtIglesia_Persona))
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtIglesiaProv_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CboMinisterio_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(37, 37, 37)
                                .addComponent(btnGuardar)
                                .addGap(32, 32, 32)
                                .addComponent(btnLimpiar)
                                .addGap(37, 37, 37)
                                .addComponent(btnModificar))
                            .addComponent(txtFechaNac_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtNombre_Persona)
                            .addComponent(lbtCedula_persona))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCedula_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(lbtId_Persona)
                                .addGap(18, 18, 18)
                                .addComponent(txtId_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbtApellido_Persona)
                                .addGap(31, 31, 31)
                                .addComponent(txtApellido_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtId_Persona)
                    .addComponent(txtId_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtCedula_persona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtNombre_Persona)
                    .addComponent(txtApellido_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtApellido_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbtFecha_Persona)
                    .addComponent(txtFechaNac_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtDirHab_Persona)
                    .addComponent(txtDirHab_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtTelfijo_Persona)
                    .addComponent(txtTelFijo_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelcel_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtTelcel_Persona))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtProfesion_Persona)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CboProfesion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtCorreo_Persona)
                        .addComponent(txtCorreo_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtIglesia_Persona)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIglesiaProv_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CboBautizado_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtBautizado_Persona)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOcupacion_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtOcupación_Persona)
                    .addComponent(CboMinisterio_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtObservacion_Persona)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModificar))
                .addGap(82, 82, 82))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "LIstado de Personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salir.png"))); // NOI18N
        btnSalir.setText("Salir");

        lbtTotal_Registros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbtTotal_Registros.setText("Número de Registro: ");

        jtPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Personas", "Cedula", "Nombre", "Apellido", "Fecha Nac", "Dirección", "Telefono", "Celular", "Profesión", "Ocupación", "Correo", "Bautizo", "Iglesia Prov", "Observación", "Ministerio"
            }
        ));
        jtPersonas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jtPersonas);

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbtFiltrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        lbtFiltrar.setText("Filtrar por:");

        jRCedula.setText("Cédula");

        jRNombre.setText("Nombre");

        jRApellido.setText("Apellido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnCancelar)
                        .addGap(60, 60, 60)
                        .addComponent(btnEliminar)
                        .addGap(42, 42, 42)
                        .addComponent(btnSalir)
                        .addGap(30, 30, 30)
                        .addComponent(lbtTotal_Registros)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtFiltrar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRCedula)
                                .addGap(18, 18, 18)
                                .addComponent(jRNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jRApellido))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnEliminar)
                            .addComponent(btnSalir)
                            .addComponent(lbtTotal_Registros)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbtFiltrar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRCedula)
                            .addComponent(jRNombre)
                            .addComponent(jRApellido))
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(330, 330, 330))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void CboMinisterio_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboMinisterio_PersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboMinisterio_PersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox CboBautizado_Persona;
    public javax.swing.JComboBox<String> CboMinisterio_Persona;
    public javax.swing.JComboBox CboProfesion_Persona;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnSalir;
    public javax.swing.ButtonGroup grupoBusqueda;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRApellido;
    public javax.swing.JRadioButton jRCedula;
    public javax.swing.JRadioButton jRNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jtPersonas;
    public javax.swing.JLabel lbtApellido_Persona;
    public javax.swing.JLabel lbtBautizado_Persona;
    public javax.swing.JLabel lbtCedula_persona;
    public javax.swing.JLabel lbtCorreo_Persona;
    public javax.swing.JLabel lbtDirHab_Persona;
    public javax.swing.JLabel lbtFecha_Persona;
    private javax.swing.JLabel lbtFiltrar;
    public javax.swing.JLabel lbtId_Persona;
    public javax.swing.JLabel lbtIglesia_Persona;
    public javax.swing.JLabel lbtNombre_Persona;
    public javax.swing.JLabel lbtObservacion_Persona;
    private javax.swing.JLabel lbtOcupación_Persona;
    public javax.swing.JLabel lbtProfesion_Persona;
    public javax.swing.JLabel lbtTelcel_Persona;
    public javax.swing.JLabel lbtTelfijo_Persona;
    public javax.swing.JLabel lbtTotal_Registros;
    public javax.swing.JTextArea tAreaObservacion_Persona;
    public javax.swing.JTextField txtApellido_Persona;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCedula_Persona;
    public javax.swing.JTextField txtCorreo_Persona;
    public javax.swing.JTextField txtDirHab_Persona;
    public com.toedter.calendar.JDateChooser txtFechaNac_Persona;
    public javax.swing.JTextField txtId_Persona;
    public javax.swing.JTextField txtIglesiaProv_Persona;
    public javax.swing.JTextField txtNombre_Persona;
    public javax.swing.JTextField txtOcupacion_Persona;
    public javax.swing.JTextField txtTelFijo_Persona;
    public javax.swing.JTextField txtTelcel_Persona;
    // End of variables declaration//GEN-END:variables
}
